name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Stop Docker Compose
        run: |
          docker-compose down --rmi local

      - name: Run Docker Compose
        run: |
          docker-compose up -d --build
          docker-compose logs
